spring.application.name=realestate
spring.datasource.url=jdbc:postgresql://db:5432/realestate
spring.datasource.username=postgres
spring.datasource.password=secretpassword
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always